services:
  db:
    image: postgres:15
    container_name: thingdex-db
    environment:
      POSTGRES_USER: thingdex
      POSTGRES_PASSWORD: thingdex
      POSTGRES_DB: thingdex
      ROOT_LOCATION_NAME: World
    ports:
      - "5432:5432"
    volumes:
      - thingdex_pgdata:/var/lib/postgresql/data
  app:
    image: python:3.13-slim
    container_name: thingdex-api
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+psycopg://thingdex:thingdex@db:5432/thingdex
      ROOT_LOCATION_NAME: World
      LABEL_PRINTING_ENABLED: "true"
      LABEL_API_BASE: http://label.xn--jahnstrae-n1a.de/api/v1
      PRINTHUB_API_BASE: http://printhub.xn--jahnstrae-n1a.de
      LABEL_CONTAINER_TEMPLATE_ID: container-name
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -lc "pip install poetry &&
      poetry install --no-root &&
      poetry run uvicorn thingdex.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  thingdex_pgdata:
